/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- find the total customers by countries
select 
	country,
	count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

-- find the total customers by gender
select 
	gender,
	count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;

-- find total product by category 
select 
	category,
	count(product_key) as total_products
from gold.dim_products
group by category
order by total_products desc;

-- find the average cost in each category
select 
	category,
	round(avg(cost),2) as average_cost
from gold.dim_products
group by category
order by average_cost desc;

-- find the total revenue generated by each category

select 
	p.category,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_products as p
on p.product_key = f.product_key
group by p.category;

-- find the total revenue generated by each customers
select 
	c.customer_id,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales as f
left join gold.dim_customers as c
on c.customer_key = f.customer_key
group by c.customer_id,
	c.first_name,
	c.last_name
order by total_revenue desc;

-- find the distribution by countries

select 
	c.country,
	sum(f.quantity) as total_sold_items
from gold.fact_sales as f
left join gold.dim_customers as c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc;
